Reproducer doesn't work
Recently I thought a failing pre-processor would cause this issue, but
it looks like that doesn't work:

```
ghci> :reload
src/MyModule.hs:1:1: error:
    `false' failed in phase `Haskell pre-processor'. (Exit code: 1)
  |
1 | {-# OPTIONS_GHC -F -pgmF false #-}
  | ^

Failed, no modules to be reloaded.
```