Move `clap-markdown` into ghciwatch source tree
`crates.io` doesn't like it:

```
error: all dependencies must have a version specified when publishing.
dependency `clap-markdown` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency
declaration.
```