Log errors in async tasks (#8)
This will actually log errors using `tracing::error!`. No more silent
errors!

The `backoff` crate does claim to support futures, but I couldn't get it
to work with my functions. Something about calling an `&mut self`
function, I think? Anyways, I can at least use their exponential backoff
implementation, which is quite nice: it supports duration caps on both
individual retry attempts and the total elapsed time, adjustable jitter,
and fractional exponents.

I'm not in love with the boilerplate duplicated between the three main
tasks, but it may have to do.

If I try to copy the [`backoff` async
example](https://github.com/ihrwein/backoff/blob/master/examples/async.rs)
like so:

```rust
backoff::future::retry(ExponentialBackoff::default(), || async move {
    match self.run_inner().await {
        Ok(()) => {
            // MPSC channel closed, probably a graceful shutdown?
            tracing::debug!("Channel closed");
            Ok(())
        }
        Err(err) => {
            tracing::error!("{err:?}");
            Err(backoff::Error::transient(err))
        }
    }
})
.await
```

I get this error:

```
error[E0507]: cannot move out of `self`, a captured variable in an `FnMut` closure
  --> src/ghci/stdin.rs:48:66
   |
47 |       pub async fn run(mut self) -> miette::Result<()> {
   |                        -------- captured outer variable
48 |           backoff::future::retry(ExponentialBackoff::default(), || async move {
   |  _______________________________________________________________--_^
   | |                                                               |
   | |                                                               captured by this `FnMut` closure
49 | |             match self.run_inner().await {
   | |                   ----
   | |                   |
   | |                   variable moved due to use in generator
   | |                   move occurs because `self` has type `GhciStdin`, which does not implement the `Copy` trait
50 | |                 Ok(()) => {
51 | |                     // MPSC channel closed, probably a graceful shutdown?
...  |
59 | |             }
60 | |         })
   | |_________^ `self` is moved here
```

If I use an `async` block instead of an `async move` block, I get this
error:

```
error: captured variable cannot escape `FnMut` closure body
  --> src/ghci/stdin.rs:48:66
   |
47 |       pub async fn run(mut self) -> miette::Result<()> {
   |                        -------- variable defined here
48 |           backoff::future::retry(ExponentialBackoff::default(), || async {
   |  ________________________________________________________________-_^
   | |                                                                |
   | |                                                                inferred to be a `FnMut` closure
49 | |             match self.run_inner().await {
   | |                   ---- variable captured here
50 | |                 Ok(()) => {
51 | |                     // MPSC channel closed, probably a graceful shutdown?
...  |
59 | |             }
60 | |         })
   | |_________^ returns an `async` block that contains a reference to a captured variable, which then escapes the closure body
   |
   = note: `FnMut` closures only have access to their captured variables while they are executing...
   = note: ...therefore, they cannot allow references to captured variables to escape
```