Fix release workflow with PRs from forks
PR #329 failed to create a release because the release workflow ran in
the context of the fork:

```
Run peter-evans/create-pull-request@v5
Error: Input 'token' not supplied. Unable to continue.
Restore git configuration
  Error: Cannot read properties of undefined (reading 'removeAuth')
```

Change the workflow to run in `pull_request_target` to fix this, I hope.

Also update `get-crate-version` to not depend on any runtime tools, only
the Nix expressions.

See: https://github.com/MercuryTechnologies/ghciwatch/actions/runs/12130981516/job/33822389311