Move `clap-markdown` into ghciwatch source tree (#271)
crates.io via `cargo publish` doesn't like it and I don't want to make
CI release two crates:

```
error: all dependencies must have a version specified when publishing.
dependency `clap-markdown` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```