Patch: Better error reporting when a watched path does not exist (#329)
Provide a more helpful error message when a watched path does not exist.
For example,

```console
$ ghciwatch --watch does-not-exist
```

**Before**
```
Error:   × Tasks failed:
  │ • run_ghci: ghci event channel closed
  │ • run_watcher: No such file or directory (os error 2)
```

**After**
```
Error:   × Tasks failed:
  │ • run_ghci: ghci event channel closed
  │ • run_watcher: Cannot watch path that doesn't exist: "/home/chris/Projects/tweag/ghciwatch/does-not-exist"
```

Partially resolves #312

- [x] Labeled the PR with `patch`, `minor`, or `major` to request a
version bump when it's merged.
- [ ] Updated the user manual in `docs/`.
- [ ] Added integration / regression tests in `tests/`.

Co-authored-by: Clément Hurlin <clement.hurlin@moduscreate.com>